credits:
  - name: Palestine Tour
    role: Clown
    company: Clowns Without Borders
  - name: Hot Mess
    role: Drag King Dick Dandy
    company: House of Yes
  - name: <i>Six Years Old World Premier Reading</i>
    role: Adailade**
    company:  The Bushwick Starr
  - name: <i>The Twilight Solution</i>
    role: Koddi
    company: Lift Off New Play Series
notes:
  - '** Nominee, Most Promising Direction, Wellington Theatre Awards 2015'
