trainings:
  - school: Dell'Arte School of Physical Theatre, CA
    name: Professional Training Programme
    year: 2018
  - school: Centrepoint Theatre, NX
    name: Directing Intern
    year: 2016
  - school: Shakespeare's Globe
    name: Emerging Theatre Practiioner's Programme
    year: 2015
  - school: Zen Zen Zo
    name: NZ Stomp
    year: 2015
  - school: University of Texas at Austin
    name: Shakespeare at Winedale
    year: 2009, 2011
  - school: University of Texas at Austin
    name: Anthropology Honours (BA)
    year: 2011
notes:
  - 'Clown:'
  - 'Butoh:'
  - 'Viewpoints/Suzuki: Lynne Bradley (Zen Zen Zo)'
