# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow # Enable drafts

collections: # A list of collections the CMS should be able to edit
  # POSTS
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - label: "Author"
        name: "author"
        widget: "select"
        options:
          - { label: "Ania Upstill", value: "ania_upstill" }
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "Description", name: "description", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Categories", name: "categories", widget: "string", required: false}
    # PAGES
  - name: "page"
    label: "Page"
    folder: "pages"
    sort: "title:asc"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Section", name: "section", widget: "hidden", default: "{{name}}"}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Video", name: "video_link", widget: "string", required: false}
    files:
      - label: 'Work'
        name: 'work'
        file: '_data/work.yml'
        fields:
          - { label: 'Theatre select performances', name: 'Theatre', widget: 'hidden', default: 'work'}
          - { label: 'Layout', name: 'page', widget: 'hidden', default: 'page' }
          - label: 'Theatre Performances'
            name: 'performance_credits'
            widget: 'list'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Role', name: 'role', widget: 'string' }
              - { label: 'Company', name: 'company', widget: 'string' }
              - { label: 'Date', name: 'date', widget: 'string' }
          - label: 'Performance notes'
            name: 'performance_notes'
            widget: 'list'
          - label: 'Production Credits'
            name: 'production_credits'
            widget: 'list'
            fields:
              - { label: 'Work', name: 'name', widget: 'string' }
              - { label: 'Role', name: 'role', widget: 'string' }
              - { label: 'Company', name: 'company', widget: 'string' }
          - label: 'Production notes'
            name: 'production_notes'
            widget: 'list'
          - label: 'Training'
            name: 'trainings'
            widget: 'list'
            fields:
              - { label: 'School', name: 'school', widget: 'string' }
              - { label: 'Programme', name: 'name', widget: 'string' }
              - { label: 'Year', name: 'year', widget: 'string' }
          - label: 'Training notes'
            name: 'training_notes'
            widget: 'list'
